import type { LivingRoomCatalogItem } from "./catalog";
import { LIVING_ROOM_MATERIAL_IDS as M } from "./materials"; // Data-only; catalog behavior stays in catalog.ts.
export const LIVING_ROOM_CATALOG_ITEMS = [
  {
    id: "living:sofa-3-seat", name: "Three Seat Sofa",
    kind: "furniture", category: "sofa", placement: "floor",
    dimensions: { widthMm: 2200, heightMm: 820, depthMm: 920 },
    materialSlots: { upholstery: M.oatmealFabric, legs: M.charcoalMetal },
    parameters: { seats: 3, cushionStyle: "loose" },
  },
  {
    id: "living:lounge-chair", name: "Lounge Chair",
    kind: "furniture", category: "chair", placement: "floor",
    dimensions: { widthMm: 820, heightMm: 880, depthMm: 860 },
    materialSlots: { upholstery: M.oliveFabric, frame: M.naturalOak },
    parameters: { seats: 1 },
  },
  {
    id: "living:coffee-table", name: "Coffee Table",
    kind: "furniture", category: "table", placement: "floor",
    dimensions: { widthMm: 1200, heightMm: 380, depthMm: 650 },
    materialSlots: { top: M.naturalOak, frame: M.charcoalMetal },
    parameters: { topShape: "rounded-rectangle" },
  },
  {
    id: "living:side-table", name: "Side Table",
    kind: "furniture", category: "table", placement: "floor",
    dimensions: { widthMm: 480, heightMm: 520, depthMm: 480 },
    materialSlots: { top: M.naturalOak, frame: M.charcoalMetal },
    parameters: { topShape: "round" },
  },
  {
    id: "living:tv-unit", name: "Floating TV Console",
    kind: "furniture", category: "media-unit", placement: "floor",
    dimensions: { widthMm: 2000, heightMm: 520, depthMm: 440 },
    materialSlots: { carcass: M.walnut, fronts: M.naturalOak },
    parameters: { doorCount: 3, cableOpening: true, floating: true, mountHeightMm: 360 },
  },
  {
    id: "living:wardrobe-wall", name: "Wardrobe Wall",
    kind: "cabinet", category: "wardrobe", placement: "wall",
    dimensions: { widthMm: 2400, heightMm: 2400, depthMm: 600 },
    materialSlots: { carcass: M.walnut, fronts: M.naturalOak },
    parameters: { doorCount: 4, shelfCount: 5, wardrobe: true },
  },
  {
    id: "living:corner-wardrobe", name: "Corner Wardrobe",
    kind: "cabinet", category: "corner-wardrobe", placement: "wall",
    dimensions: { widthMm: 900, heightMm: 2200, depthMm: 600 },
    materialSlots: { carcass: M.walnut, fronts: M.naturalOak },
    parameters: { doorCount: 1, shelfCount: 4, corner: true, legWidthMm: 900 },
  },
  {
    id: "living:tall-pantry-600", name: "Tall Pantry · 600",
    kind: "cabinet", category: "storage", placement: "wall",
    dimensions: { widthMm: 600, heightMm: 2400, depthMm: 600 },
    materialSlots: { carcass: M.walnut, fronts: M.naturalOak },
    parameters: { sku: "MW-TALL-600", doorCount: 2, shelfCount: 5, pantry: true },
  },
  {
    id: "living:base-cabinet-900", name: "Base Cabinet · 900",
    kind: "cabinet", category: "storage", placement: "wall",
    dimensions: { widthMm: 900, heightMm: 900, depthMm: 600 },
    materialSlots: { carcass: M.walnut, fronts: M.naturalOak },
    parameters: { sku: "MW-BASE-900", doorCount: 2, drawerCount: 1, baseCabinet: true },
  },
  {
    id: "living:wall-cabinet-900", name: "Wall Cabinet · 900",
    kind: "cabinet", category: "storage", placement: "wall",
    dimensions: { widthMm: 900, heightMm: 720, depthMm: 350 },
    materialSlots: { carcass: M.walnut, fronts: M.naturalOak },
    parameters: { sku: "MW-WALL-900", doorCount: 2, wallCabinet: true },
  },
  {
    id: "living:feature-wall-fluted", name: "Fluted Timber TV Feature Wall",
    kind: "cabinet", category: "feature-wall", placement: "wall",
    dimensions: { widthMm: 3600, heightMm: 2200, depthMm: 62 },
    materialSlots: { backing: M.walnut, slats: M.naturalOak, trim: M.walnut },
    parameters: { slatWidthMm: 46, slatGapMm: 18, edgeRailMm: 56 },
  },
  {
    id: "living:display-niche", name: "Lit Display Niche",
    kind: "cabinet", category: "display-niche", placement: "wall",
    dimensions: { widthMm: 560, heightMm: 1900, depthMm: 280 },
    materialSlots: { carcass: M.walnut, back: M.charcoalMetal, shelves: M.naturalOak },
    parameters: { shelfCount: 4, integratedLight: true },
  },
  {
    id: "living:decor-vase", name: "Ceramic Display Vase",
    kind: "decor", category: "accessory", placement: "wall",
    dimensions: { widthMm: 180, heightMm: 320, depthMm: 180 },
    materialSlots: { surface: M.walnut },
    parameters: { style: "tapered" },
  },
  {
    id: "living:decor-sculpture", name: "Display Sculpture",
    kind: "decor", category: "accessory", placement: "wall",
    dimensions: { widthMm: 220, heightMm: 260, depthMm: 150 },
    materialSlots: { surface: M.naturalOak },
    parameters: { style: "rounded" },
  },
  {
    id: "living:ceiling-fan", name: "Contemporary Ceiling Fan",
    kind: "furniture", category: "ceiling-fixture", placement: "wall",
    dimensions: { widthMm: 1450, heightMm: 260, depthMm: 1450 },
    materialSlots: { metal: M.charcoalMetal, blades: M.walnut },
    parameters: { bladeCount: 4 },
  },
  {
    id: "living:curtain-set", name: "Full Height Curtain Set",
    kind: "decor", category: "window-treatment", placement: "wall",
    dimensions: { widthMm: 2200, heightMm: 2100, depthMm: 70 },
    materialSlots: { fabric: M.oatmealFabric, rail: M.charcoalMetal },
    parameters: { panelCount: 2, fullness: "soft" },
  },
  {
    id: "living:area-rug", name: "Area Rug",
    kind: "decor", category: "rug", placement: "floor",
    dimensions: { widthMm: 3000, heightMm: 18, depthMm: 2200 },
    materialSlots: { surface: M.woolRug },
    parameters: { pile: "low" },
  },
  {
    id: "living:wall-mirror", name: "Wall Mirror",
    kind: "decor", category: "mirror", placement: "wall",
    dimensions: { widthMm: 900, heightMm: 1400, depthMm: 35 },
    materialSlots: { mirror: M.clearGlass, frame: M.charcoalMetal },
    parameters: { mountHeightMm: 850 },
  },
  {
    id: "living:floor-lamp", name: "Floor Lamp",
    kind: "lighting", category: "floor-lamp", placement: "floor",
    dimensions: { widthMm: 420, heightMm: 1650, depthMm: 420 },
    materialSlots: { frame: M.charcoalMetal, shade: M.oatmealFabric },
    parameters: { bulbTemperatureK: 2700, lumens: 800 },
  },
  {
    id: "living:sofa-sectional", name: "Modular Sectional",
    kind: "furniture", category: "sofa", placement: "floor",
    dimensions: { widthMm: 2950, heightMm: 800, depthMm: 1750 },
    materialSlots: { upholstery: M.oatmealFabric, legs: M.charcoalMetal },
    parameters: { seats: 4, cushionStyle: "modular", chaise: true },
  },
  {
    id: "living:sofa-loveseat", name: "Compact Loveseat",
    kind: "furniture", category: "sofa", placement: "floor",
    dimensions: { widthMm: 1650, heightMm: 790, depthMm: 860 },
    materialSlots: { upholstery: M.oliveFabric, legs: M.naturalOak },
    parameters: { seats: 2, cushionStyle: "tight" },
  },
  {
    id: "living:accent-chair", name: "Sculpted Accent Chair",
    kind: "furniture", category: "chair", placement: "floor",
    dimensions: { widthMm: 760, heightMm: 820, depthMm: 780 },
    materialSlots: { upholstery: M.oatmealFabric, frame: M.walnut },
    parameters: { seats: 1, silhouette: "sculpted" },
  },
  {
    id: "living:coffee-table-round", name: "Round Coffee Table",
    kind: "furniture", category: "table", placement: "floor",
    dimensions: { widthMm: 900, heightMm: 360, depthMm: 900 },
    materialSlots: { top: M.walnut, frame: M.charcoalMetal },
    parameters: { topShape: "round" },
  },
  {
    id: "living:console-table", name: "Slim Console Table",
    kind: "furniture", category: "table", placement: "floor",
    dimensions: { widthMm: 1500, heightMm: 780, depthMm: 360 },
    materialSlots: { top: M.naturalOak, frame: M.charcoalMetal },
    parameters: { topShape: "rectangle" },
  },
  {
    id: "living:bookcase", name: "Open Bookcase",
    kind: "furniture", category: "storage", placement: "floor",
    dimensions: { widthMm: 1100, heightMm: 2100, depthMm: 360 },
    materialSlots: { carcass: M.naturalOak },
    parameters: { shelfCount: 5 },
  },
  {
    id: "living:ottoman", name: "Upholstered Ottoman",
    kind: "furniture", category: "seat", placement: "floor",
    dimensions: { widthMm: 820, heightMm: 420, depthMm: 620 },
    materialSlots: { upholstery: M.oliveFabric, base: M.walnut },
    parameters: { silhouette: "soft-square" },
  },
  {
    id: "living:indoor-plant", name: "Indoor Plant",
    kind: "decor", category: "plant", placement: "floor",
    dimensions: { widthMm: 720, heightMm: 1450, depthMm: 720 },
    materialSlots: { foliage: M.oliveFabric, planter: M.woolRug },
    parameters: { foliageStyle: "broad-leaf" },
  },
  {
    id: "living:structural-column", name: "Structural Column",
    kind: "custom", category: "structural-column", placement: "floor",
    dimensions: { widthMm: 300, heightMm: 2800, depthMm: 300 },
    materialSlots: { finish: M.wallPaint },
    parameters: { profile: "square", structural: true },
  },
] as const satisfies readonly LivingRoomCatalogItem[];
