import type { CardMediaEntry, TemplateCardId } from "./types";
import data from "./cardMedia.generated.json";

/** Generated by `npm run media:cards`. Safe to commit after capture. */
export const CARD_MEDIA = data as Record<TemplateCardId, CardMediaEntry>;
