import { useState } from "react";
import type { InteriorProject } from "../../domain/interiorProject";
import { useAccountPlan } from "../../hooks/useAccountPlan";
import { notifyCommercialStorageChanged } from "../../hooks/useCommercialStorageRevision";
import { persistLocalAccount } from "../../domain/saas";
import { createEmptyOrganizationStub, type CompanyRole, type OrganizationStub } from "../../domain/saas/companySchema";
import { addSeat, ensureOwnerSeat, findSeatByEmail, seatHasPermission, setSeatActive, updateSeatRole, readCompanyControls, persistCompanyControls, setSeatProjectAccess, ownerDashboardForProjects, requestApproval, approveRequest, rejectRequest, cancelRequest, type CompanyControlsState, type ProjectAccessLevel } from "../../domain/company";
import { readPaymentLedger } from "../../domain/paymentLedger";
import { readProposalCommercial } from "../../domain/livingRoom/proposal/commercialState";

export function InteriorCompanyPanel({ project }: { project: InteriorProject }) {
  const account = useAccountPlan();
  const [tick, setTick] = useState(0), [email, setEmail] = useState(""), [role, setRole] = useState<CompanyRole>("designer"), [reason, setReason] = useState(""), [message, setMessage] = useState("");
  void tick;
  const org = account.account?.organization;
  const seat = org && account.account ? findSeatByEmail(org, account.account.email) : undefined;
  const controls = org ? readCompanyControls(org.id) : null;
  const snapshot = readProposalCommercial(project).quoteHistory[0];
  const can = (permission: Parameters<typeof seatHasPermission>[1]) => Boolean(seat && seatHasPermission(seat, permission));
  function run(action: () => void) { try { action(); setTick(v => v + 1); account.refresh(); notifyCommercialStorageChanged(); setMessage("Company settings saved locally."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save."); } }
  function saveOrg(next: OrganizationStub) { if (!account.account || !can("seats:manage")) throw new Error("Seat management requires an owner."); persistLocalAccount({ ...account.account, organization: next }); }
  function saveControls(next: CompanyControlsState) { persistCompanyControls(next); }
  if (!account.entitlements.canUseCompanyControls) return <section><h3>Company workspace</h3><p>Company includes seats, project access, approvals and owner reporting.</p></section>;
  const dashboard = controls && can("dashboard:view") ? ownerDashboardForProjects(readPaymentLedger(), controls.sharedProjects.projects.filter(p => seat?.role === "owner" || (seat && p.grants[seat.id] && p.grants[seat.id] !== "none")).map(p => p.projectId)) : null;
  return <section><h3>Company workspace · local preview</h3><p>These controls are stored on this device. Adding a seat records access settings; it does not send an invitation or sync projects to another computer. Approval decisions are recorded here; release enforcement is not yet connected.</p><p role="status">{message}</p>
    {(!org || org.seats.length === 0) && <button type="button" onClick={() => run(() => { if (!account.account) throw new Error("Sign in first."); persistLocalAccount({ ...account.account, organization: ensureOwnerSeat(org ?? createEmptyOrganizationStub(account.account.companyName), { email: account.account.email }) }); })}>Initialize local owner workspace</button>}
    {org && controls && <><h4>{org.name}</h4><form className="ipt-fields" onSubmit={e => { e.preventDefault(); run(() => saveOrg(addSeat(org, { email, role }))); }}><fieldset disabled={!can("seats:manage")} className="ipt-fields"><label>Seat email<input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label>Role<select value={role} onChange={e => setRole(e.target.value as CompanyRole)}><option value="designer">Designer</option><option value="engineer">Engineer</option><option value="viewer">Viewer</option></select></label><button>Add local seat</button></fieldset></form>
      <div className="ipt-table"><table><thead><tr><th>Seat</th><th>Role</th><th>Active</th><th>This project access</th></tr></thead><tbody>{org.seats.map(member => <tr key={member.id}><td>{member.email}</td><td><select aria-label={`Role for ${member.email}`} disabled={!can("seats:manage")} value={member.role} onChange={e => run(() => saveOrg(updateSeatRole(org, member.id, e.target.value as CompanyRole)))}>{["owner", "designer", "engineer", "viewer"].map(r => <option key={r}>{r}</option>)}</select></td><td><input type="checkbox" aria-label={`Active ${member.email}`} disabled={!can("seats:manage")} checked={member.active} onChange={e => run(() => saveOrg(setSeatActive(org, member.id, e.target.checked)))} /></td><td>{member.role === "owner" ? "Owner" : <select aria-label={`Project access for ${member.email}`} disabled={!can("projects:share")} value={controls.sharedProjects.projects.find(p => p.projectId === project.id)?.grants[member.id] ?? "none"} onChange={e => run(() => { if (!seat) throw new Error("Missing seat"); saveControls({ ...controls, sharedProjects: setSeatProjectAccess(controls.sharedProjects, { org, projectId: project.id, seatId: member.id, actorSeatId: seat.id, access: e.target.value as ProjectAccessLevel }) }); })}>{["none", "view", "edit", "manage"].map(a => <option key={a}>{a}</option>)}</select>}</td></tr>)}</tbody></table></div>
      {dashboard && <><h4>Current obligations · shared projects</h4><p>{dashboard.projectCount} projects · Quoted {dashboard.quoted} · Accepted {dashboard.accepted} · Invoiced {dashboard.invoiced} · Received {dashboard.received} · Outstanding {dashboard.outstanding} · Overdue {dashboard.overdue}</p></>}
      <h4>Proposal approval records</h4><label>Request note / decision reason<input value={reason} onChange={e => setReason(e.target.value)} /></label><button type="button" disabled={!snapshot || !can("approvals:request")} onClick={() => run(() => { if (!seat || !snapshot || !can("approvals:request")) throw new Error("A frozen quote and requester seat are required."); saveControls({ ...controls, approvals: requestApproval(controls.approvals, { projectId: project.id, kind: "quote_export", requestedBySeatId: seat.id, quoteSnapshotId: snapshot.id, revisionLabel: snapshot.revision, note: reason }).state }); })}>Request approval for current frozen quote</button>
      {controls.approvals.requests.filter(r => r.projectId === project.id).map(request => <article key={request.id}><p>{request.revisionLabel} · {request.kind} · {request.status} · {request.createdAt}</p><small>{request.reason ?? request.note}</small>{request.status === "pending" && <div className="ipt-fields">{(["Approve", "Reject", "Cancel"] as const).map(action => <button type="button" key={action} disabled={!seat || (action === "Cancel" ? request.requestedBySeatId !== seat.id && !can("approvals:decide") : !can("approvals:decide") || request.requestedBySeatId === seat.id)} onClick={() => run(() => { if (!seat) throw new Error("Missing seat"); const decide = action === "Approve" ? approveRequest : action === "Reject" ? rejectRequest : cancelRequest; saveControls({ ...controls, approvals: decide(controls.approvals, { requestId: request.id, decidedBySeatId: seat.id, decidedBySeat: seat, reason }) }); })}>{action}</button>)}</div>}</article>)}
    </>}
  </section>;
}
