import type { InteriorProject, InteriorRoomEntity, OpeningEntity } from "../../domain/interiorProject";
import type { LivingRoomPlanUnderlay } from "../../domain/livingRoom/planUnderlay";
import type { BuildTool, LivingRoomPlanIssue, LivingRoomRenderResult, PlanReadabilitySettings } from "../../domain/livingRoom";
import type { LivingRoomPlanWorkspaceProps, LivingRoomWorkspaceView, PlannerMode, StudioPanel } from "./workspaceProps";
import type { useLivingRoomBuildCommands } from "../../hooks/useLivingRoomBuildCommands";
import type { useMillworkSchedule } from "../../hooks/useMillworkSchedule";
import type { useClientPresentationExport } from "../../hooks/useClientPresentationExport";
import type { AcceptedStillAsset } from "../../hooks/selectPackageAcceptedStillAssets";

type BuildBridge = ReturnType<typeof useLivingRoomBuildCommands>;
type Millwork = ReturnType<typeof useMillworkSchedule>;
type ClientExport = ReturnType<typeof useClientPresentationExport>;

export type LivingRoomPlanWorkspaceBodyProps = {
  workspace: LivingRoomPlanWorkspaceProps;
  project: InteriorProject;
  room: InteriorRoomEntity;
  underlay: LivingRoomPlanUnderlay | null;
  workspaceView: LivingRoomWorkspaceView;
  plannerMode: PlannerMode;
  studioPanel: StudioPanel;
  onStudioPanel: (panel: StudioPanel) => void;
  assetQuery: string;
  assetCategory: string;
  assetCategories: string[];
  importError: string;
  onAssetQuery: (value: string) => void;
  onAssetCategory: (value: string) => void;
  onImportError: (message: string) => void;
  snapSizeMm: number;
  showGrid: boolean;
  onShowGrid: (value: boolean) => void;
  onSnapSize: (value: number) => void;
  activeWallId: string | null;
  activeOpeningId: string | null;
  activeSurfaceId: string | null;
  setActiveSurfaceId: React.Dispatch<React.SetStateAction<string | null>>;
  activeOpening: OpeningEntity | null;
  setActiveWallId: React.Dispatch<React.SetStateAction<string | null>>;
  setActiveOpeningId: React.Dispatch<React.SetStateAction<string | null>>;
  roomPolygonPointCount: number;
  roomPolygonCloseRequest: number;
  onRoomPolygonPointCount: (count: number) => void;
  onRoomPolygonCloseRequest: () => void;
  renderResults: { latest: LivingRoomRenderResult | null; previous: LivingRoomRenderResult | null };
  onRenderResults: (result: LivingRoomRenderResult) => void;
  build: BuildBridge;
  activeBuildTool: BuildTool;
  onBuildTool: (tool: BuildTool) => void;
  underlayPickerRef: React.RefObject<(() => void) | null>;
  millwork: Millwork;
  clientExport: ClientExport;
  acceptedStillAssets: AcceptedStillAsset[];
  onAcceptedStillAssetsChange: React.Dispatch<React.SetStateAction<AcceptedStillAsset[]>>;
  issues: LivingRoomPlanIssue[];
  readability: PlanReadabilitySettings;
  onReadability: (patch: Partial<PlanReadabilitySettings>) => void;
};
