import type { InteriorObjectEntity } from "../../domain/interiorProject";
import { getCabinetMechanismState, mechanismAllPatch, mechanismPanelPatch } from "../../domain/livingRoom";
type Props = { object: InteriorObjectEntity | null; onChange: (id: string, patch: Record<string, string | number | boolean>) => void; onSoftClose: (object: InteriorObjectEntity) => void };
/** Model-view controls for individually animated cabinet fronts. */
export function CabinetMechanismPanel({ object, onChange, onSoftClose }: Props) {
  const state = object ? getCabinetMechanismState(object) : null;
  if (!object || !state) return null;
  const set = (patch: Record<string, string | number | boolean>) => onChange(object.id, patch);
  return <aside className="lr-mechanism-panel" aria-label="Cabinet mechanisms"><header><strong>FRONTS</strong><span>{state.mode === "drawer" ? "Pull-out drawers" : "Swing doors"}</span></header><label>Type<select value={state.mode} onChange={(e) => set({ frontMode: e.target.value })}><option value="drawer">Drawer</option><option value="door">Door</option></select></label><label>Pull depth <input type="range" min="80" max={Math.max(100, Math.round(object.dimensions.depthMm * .9))} step="10" value={state.pullDepthMm} onChange={(e) => set({ pullDepthMm: Number(e.target.value) })} /><b>{state.pullDepthMm} mm</b></label><div className="lr-mechanism-fronts">{state.open.map((open, index) => <button key={index} className={open ? "is-open" : ""} type="button" onClick={() => set(mechanismPanelPatch(index, !open))}>{state.mode === "drawer" ? "Drawer" : "Door"} {index + 1}<small>{open ? "Open" : "Closed"}</small></button>)}</div><div className="lr-mechanism-actions"><button type="button" onClick={() => set(mechanismAllPatch(state, true))}>Open all</button><button type="button" onClick={() => set(mechanismAllPatch(state, false))}>Close all</button></div><label className="lr-mechanism-toggle"><input type="checkbox" checked={state.softClose} onChange={(e) => set({ softClose: e.target.checked })} /> Soft-close enabled</label>{state.softClose ? <button type="button" onClick={() => onSoftClose(object)}>Preview soft-close</button> : null}</aside>;
}
