import type { RefObject } from "react";
import type { RenderQuality } from "../../domain/interiorProject";
import type { CompiledLivingRoomScene, LivingRoomStyleId, PresetHonestyDescription } from "../../domain/livingRoom";
import type { ModelViewCameraOverrides } from "../../domain/livingRoom/modelViewCameraOverrides";
import type { EnvironmentLightingQuality } from "../../domain/livingRoom/environmentLightingQuality";
import type { RenderMode } from "../../domain/livingRoom/renderAssetContracts";
import { modelViewClientPresentationProps } from "../../domain/livingRoom/modelViewClientPresentation";
import { useApartmentOverview } from "../../hooks/useApartmentOverview";
import { useModelViewCameraSession } from "../../hooks/useModelViewCameraSession";
import { useModelViewTransform } from "../../hooks/useModelViewTransform";
import { useRenderDiagnostics } from "../../hooks/useRenderDiagnostics";
import { useShowcaseTour } from "../../hooks/useShowcaseTour";
import type { LivingRoomModelViewProps } from "../livingRoomModelViewProps";
import type { WallContextMenuState } from "./ModelWallVisibilityHost";

export type LivingRoomModelViewportProps = {
  handlers: LivingRoomModelViewProps;
  camera: ReturnType<typeof useModelViewCameraSession>;
  tour: ReturnType<typeof useShowcaseTour>;
  scene: CompiledLivingRoomScene;
  overview: ReturnType<typeof useApartmentOverview>;
  canvasHostRef: RefObject<HTMLDivElement | null>;
  showGuide: boolean;
  onShowGuide: (show: boolean) => void;
  cameraHeightMm: number;
  onCameraHeightMm: (value: number) => void;
  fieldOfViewDegrees: number;
  onFieldOfViewDegrees: (value: number) => void;
  cutawayWalls: boolean;
  onCutawayWalls: (value: boolean) => void;
  showCeiling: boolean;
  onShowCeiling: (value: boolean) => void;
  wallResize?: import("./ModelWallResizeHandles").WallResizeHandlesProps;
  wallMenu: WallContextMenuState | null;
  onWallMenu: (menu: WallContextMenuState | null) => void;
  viewportQuality: RenderQuality;
  onViewportQuality: (quality: RenderQuality) => void;
  honesty: PresetHonestyDescription;
  activeStyleId: LivingRoomStyleId;
  activeStyleName: string;
  transform: ReturnType<typeof useModelViewTransform>;
  activeCameraId: string | null;
  onActiveCameraId: (cameraId: string | null) => void;
  diagnostics: ReturnType<typeof useRenderDiagnostics>;
  cameraOverrides: ModelViewCameraOverrides;
  viewOnly: boolean;
  clientView: ReturnType<typeof modelViewClientPresentationProps>;
  hoveredRoomId: string | null;
  onHoverRoom: (roomId: string | null) => void;
  onActivateRoom: (roomId: string) => void;
  showStylePalette: boolean;
  presentation: boolean;
  profile: unknown;
  ceilingHidden: boolean;
  nearWallCut: boolean;
  lightScale: number;
  windowScale: number;
  roomLightScale: number;
  renderMode: RenderMode;
  lightingQuality: EnvironmentLightingQuality;
  planTrace: boolean;
  onRotate: (rotationY: number) => void;
  onMechanism: (objectId: string, primitiveId: string) => void;
  onApplyStyle: LivingRoomModelViewProps["onApplyStyle"];
  onSetParameters: LivingRoomModelViewProps["onSetParameters"];
  onPatchDocument: LivingRoomModelViewProps["onPatchDocument"];
  onSelect: LivingRoomModelViewProps["onSelect"];
  onClearSelection: LivingRoomModelViewProps["onClearSelection"];
  snapSizeMm: number;
  activeLightId: string | null;
  captureFixedDpr?: number;
};
