export type {
  CabinetComposition,
  CabinetConstructionSpec,
  ProjectDrafting,
  DraftingDisplayPreferences,
  QuoteSettings,
  QuoteSnapshot,
  SheetOptimizerSettings,
  CabinetHardwareSpec,
  CabinetType,
  CabinetDimensions,
  CabinetConfig,
  CabinetPlacement,
  CabinetInstance,
  CabinetLayer,
  CabinetGroup,
  ProjectPreferences,
  RoomBounds,
  CabinetProject,
} from "./types";

export {
  isStorageType,
  supportsCountertop,
  supportsDoors,
  supportsDrawers,
  supportsEndPanels,
  supportsShelves,
  supportsToeKick,
  supportsWallPlacement,
} from "../cabinetCapabilities";

export {
  CABINET_WIDTH_MIN_MM,
  CABINET_WIDTH_MAX_MM,
  CABINET_WIDTH_STEP_MM,
  CABINET_HEIGHT_MIN_MM,
  CABINET_HEIGHT_MAX_MM,
  CABINET_HEIGHT_STEP_MM,
  CABINET_DEPTH_MIN_MM,
  CABINET_DEPTH_MAX_MM,
  CABINET_DEPTH_STEP_MM,
  CABINET_SHELF_MIN,
  CABINET_SHELF_MAX,
  CABINET_DRAWER_MIN,
  CABINET_DRAWER_MAX,
  CABINET_TOE_KICK_HEIGHT_MIN_MM,
  CABINET_TOE_KICK_HEIGHT_MAX_MM,
  CABINET_TOE_KICK_INSET_MIN_MM,
  CABINET_TOE_KICK_INSET_MAX_MM,
  CABINET_GRID_SNAP_MM,
  CABINET_CLEARANCE_MM,
  ROOM_WIDTH_MM,
  ROOM_DEPTH_MM,
  ROOM_HEIGHT_MM,
  cabinetTypeLabels,
  getDefaultCabinetConfig,
  defaultCabinetConfig,
  defaultCabinetProject,
} from "./defaults";

export {
  clampCabinetWidth,
  clampCabinetHeight,
  clampCabinetDepth,
  clampShelfCount,
  clampDrawerCount,
  clampToeKickHeight,
  clampToeKickInset,
  clampCabinetDimensions,
  clampCabinetConfig,
  clampCabinetProject,
} from "./clamps";

export {
  millimetresToMetres,
  normalizeRotationAngle,
  usesRotatedFootprint,
  getFootprintDimensions,
  getDefaultBottomOffsetMm,
  snapMillimetresToGrid,
  clampCabinetPlacement,
  getWallPlacement,
  cabinetsOverlap,
  projectHasCollision,
} from "./placement";

export { getCabinetValidationMessages } from "./validation";
