import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const JSON_NAME = "cardMedia.generated.json";

export function posterEntry(w800, w1600) {
  return { poster: { w800, w1600 } };
}

export function apartmentEntry(w800, w1600, plan800, plan1600) {
  return { poster: { w800, w1600 }, plan: { w800: plan800, w1600: plan1600 } };
}

export function cardMediaJsonPath(root) {
  return join(root, "src/domain/templateCardMedia", JSON_NAME);
}

/** @returns {Record<string, import('../../src/domain/templateCardMedia/types.ts').CardMediaEntry>} */
export async function readExistingCardMedia(root) {
  const path = cardMediaJsonPath(root);
  let raw;
  try {
    raw = await readFile(path, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return {};
    }
    throw error;
  }
  try {
    return JSON.parse(raw);
  } catch (error) {
    throw new Error(`Invalid ${JSON_NAME}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

export async function writeCardMediaManifest(root, entries) {
  const existing = await readExistingCardMedia(root);
  const merged = { ...existing, ...entries };
  const jsonPath = cardMediaJsonPath(root);
  await writeFile(jsonPath, `${JSON.stringify(merged, null, 2)}\n`);
  const tsPath = join(root, "src/domain/templateCardMedia/cardMedia.generated.ts");
  const source = `import type { CardMediaEntry, TemplateCardId } from "./types";
import data from "./${JSON_NAME}";

/** Generated by \`npm run media:cards\`. Safe to commit after capture. */
export const CARD_MEDIA = data as Record<TemplateCardId, CardMediaEntry>;
`;
  await writeFile(tsPath, source);
  return { jsonPath, tsPath };
}
