import { LIVING_ROOM_MATERIAL_IDS } from "../../domain/livingRoom/materials";
import type { MaterialAssetDefinition } from "../../domain/livingRoom/renderAssetContracts";

/** PBR material spine for living-room materials. Maps stay procedural until files land. */
export const MATERIAL_ASSET_MANIFEST = [
  {
    id: LIVING_ROOM_MATERIAL_IDS.wallPaint,
    name: "Warm White Wall Paint",
    kind: "paint",
    baseColor: "#e9e3d8",
    roughness: 0.86,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 2400,
    colorMapId: "tex:paint-wall-color",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.ceilingPaint,
    name: "Soft White Ceiling Paint",
    kind: "paint",
    baseColor: "#f5f2eb",
    roughness: 0.9,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 3200,
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.naturalOak,
    name: "Natural Oak",
    kind: "wood",
    baseColor: "#b98a58",
    roughness: 0.62,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 900,
    colorMapId: "tex:oak-color",
    normalMapId: "tex:oak-normal",
    roughnessMapId: "tex:oak-rough",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.walnut,
    name: "Smoked Walnut",
    kind: "wood",
    baseColor: "#5a3928",
    roughness: 0.56,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 900,
    colorMapId: "tex:walnut-color",
    normalMapId: "tex:walnut-normal",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.oatmealFabric,
    name: "Oatmeal Weave",
    kind: "fabric",
    baseColor: "#c8baa6",
    roughness: 0.96,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 450,
    colorMapId: "tex:fabric-oatmeal-color",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.oliveFabric,
    name: "Olive Weave",
    kind: "fabric",
    baseColor: "#73765a",
    roughness: 0.95,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 450,
    colorMapId: "tex:fabric-olive-color",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.charcoalMetal,
    name: "Charcoal Powder Coat",
    kind: "metal",
    baseColor: "#2d302f",
    roughness: 0.36,
    metalness: 0.72,
    opacity: 1,
    uvScaleMm: 600,
    aoMapId: "tex:metal-ao",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.clearGlass,
    name: "Clear Glass",
    kind: "glass",
    baseColor: "#d8e4e2",
    roughness: 0.08,
    metalness: 0,
    opacity: 0.32,
    uvScaleMm: 1200,
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.woolRug,
    name: "Sand Wool Rug",
    kind: "fabric",
    baseColor: "#b8a68d",
    roughness: 1,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 1600,
    colorMapId: "tex:rug-wool-color",
    proceduralFallback: true,
  },
] as const satisfies readonly MaterialAssetDefinition[];
