import { LIVING_ROOM_MATERIAL_IDS } from "../../domain/livingRoom/materials";
import type { MaterialAssetDefinition } from "../../domain/livingRoom/renderAssetContracts";

/** PBR material spine for living-room materials — curated maps + procedural fallback. */
export const MATERIAL_ASSET_MANIFEST = [
  {
    id: LIVING_ROOM_MATERIAL_IDS.wallPaint,
    name: "Warm White Wall Paint",
    kind: "paint",
    baseColor: "#ebe6dc",
    roughness: 0.9,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 2400,
    colorMapId: "tex:paint-wall-color",
    normalMapId: "tex:paint-wall-normal",
    roughnessMapId: "tex:paint-wall-rough",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.ceilingPaint,
    name: "Soft White Ceiling Paint",
    kind: "paint",
    baseColor: "#f5f2eb",
    roughness: 0.9,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 3200,
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.naturalOak,
    name: "Natural Oak",
    kind: "wood",
    baseColor: "#c4925c",
    roughness: 0.56,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 900,
    colorMapId: "tex:oak-color",
    normalMapId: "tex:oak-normal",
    roughnessMapId: "tex:oak-rough",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.walnut,
    name: "Smoked Walnut",
    kind: "wood",
    baseColor: "#4a2e20",
    roughness: 0.5,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 900,
    colorMapId: "tex:walnut-color",
    normalMapId: "tex:walnut-normal",
    roughnessMapId: "tex:walnut-rough",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.oatmealFabric,
    name: "Oatmeal Weave",
    kind: "fabric",
    baseColor: "#d2c3ae",
    roughness: 0.97,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 450,
    colorMapId: "tex:fabric-oatmeal-color",
    normalMapId: "tex:fabric-oatmeal-normal",
    roughnessMapId: "tex:fabric-oatmeal-rough",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.oliveFabric,
    name: "Olive Weave",
    kind: "fabric",
    baseColor: "#6a6e52",
    roughness: 0.97,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 450,
    colorMapId: "tex:fabric-olive-color",
    normalMapId: "tex:fabric-olive-normal",
    roughnessMapId: "tex:fabric-olive-rough",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.charcoalMetal,
    name: "Charcoal Powder Coat",
    kind: "metal",
    baseColor: "#2d302f",
    roughness: 0.36,
    metalness: 0.72,
    opacity: 1,
    uvScaleMm: 600,
    aoMapId: "tex:metal-ao",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.clearGlass,
    name: "Clear Glass",
    kind: "glass",
    baseColor: "#d8e4e2",
    roughness: 0.08,
    metalness: 0,
    opacity: 0.32,
    uvScaleMm: 1200,
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.woolRug,
    name: "Sand Wool Rug",
    kind: "fabric",
    baseColor: "#a89478",
    roughness: 1,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 1600,
    colorMapId: "tex:rug-wool-color",
    normalMapId: "tex:rug-wool-normal",
    roughnessMapId: "tex:rug-wool-rough",
    proceduralFallback: true,
  },
  {
    id: LIVING_ROOM_MATERIAL_IDS.warmStone,
    name: "Warm Honed Stone",
    kind: "stone",
    baseColor: "#d8d1c5",
    roughness: 0.48,
    metalness: 0,
    opacity: 1,
    uvScaleMm: 1800,
    colorMapId: "tex:stone-warm-color",
    normalMapId: "tex:stone-warm-normal",
    roughnessMapId: "tex:stone-warm-rough",
    proceduralFallback: true,
  },
] as const satisfies readonly MaterialAssetDefinition[];
