/** Viewport KTX2 urls. Keys match `SCANNED_MATERIAL_SETS` texture ids. */
export const SCANNED_TEXTURE_URLS: Record<string, string> = {
  "tex:oak-color": "/textures/wood/oak-color.ktx2",
  "tex:oak-normal": "/textures/wood/oak-normal.ktx2",
  "tex:oak-rough": "/textures/wood/oak-rough.ktx2",
  "tex:walnut-color": "/textures/wood/walnut-color.ktx2",
  "tex:walnut-normal": "/textures/wood/walnut-normal.ktx2",
  "tex:walnut-rough": "/textures/wood/walnut-rough.ktx2",
  "tex:fabric-oatmeal-color": "/textures/fabric/oatmeal-color.ktx2",
  "tex:fabric-oatmeal-normal": "/textures/fabric/oatmeal-normal.ktx2",
  "tex:fabric-oatmeal-rough": "/textures/fabric/oatmeal-rough.ktx2",
  "tex:fabric-olive-color": "/textures/fabric/olive-color.ktx2",
  "tex:fabric-olive-normal": "/textures/fabric/olive-normal.ktx2",
  "tex:fabric-olive-rough": "/textures/fabric/olive-rough.ktx2",
  "tex:stone-warm-color": "/textures/stone/warm-color.ktx2",
  "tex:stone-warm-normal": "/textures/stone/warm-normal.ktx2",
  "tex:stone-warm-rough": "/textures/stone/warm-rough.ktx2",
  "tex:paint-wall-color": "/textures/paint/wall-color.ktx2",
  "tex:paint-wall-normal": "/textures/paint/wall-normal.ktx2",
  "tex:paint-wall-rough": "/textures/paint/wall-rough.ktx2",
  "tex:laminate-white-color": "/textures/laminate/white-color.ktx2",
  "tex:laminate-white-normal": "/textures/laminate/white-normal.ktx2",
  "tex:laminate-white-rough": "/textures/laminate/white-rough.ktx2",
  "tex:laminate-grey-color": "/textures/laminate/grey-color.ktx2",
  "tex:laminate-grey-normal": "/textures/laminate/grey-normal.ktx2",
  "tex:laminate-grey-rough": "/textures/laminate/grey-rough.ktx2",
};
