import type { ModelAssetDefinition } from "../../domain/livingRoom/renderAssetContracts";

/**
 * Soft-goods GLB manifest. Scoped starter assets are available under /public.
 * assetKey is registry metadata only — never written into InteriorProject JSON.
 */
export const MODEL_ASSET_MANIFEST = [
  {
    id: "model:sofa-3-seat",
    name: "Three Seat Sofa",
    catalogItemId: "living:sofa-3-seat",
    assetKey: "models/soft-goods/sofa-3-seat.glb",
    available: true,
    defaultUvScaleMm: 900,
    nativeSizeMm: { widthMm: 2200, heightMm: 820, depthMm: 920 },
    materialGroups: { upholstery: "upholstery", legs: "legs" },
  },
  {
    id: "model:sofa-sectional",
    name: "Modular Sectional",
    catalogItemId: "living:sofa-sectional",
    assetKey: "models/soft-goods/sofa-sectional.glb",
    available: false,
    defaultUvScaleMm: 900,
    nativeSizeMm: { widthMm: 2950, heightMm: 800, depthMm: 1750 },
    materialGroups: { upholstery: "upholstery", legs: "legs" },
  },
  {
    id: "model:sofa-loveseat",
    name: "Compact Loveseat",
    catalogItemId: "living:sofa-loveseat",
    assetKey: "models/soft-goods/sofa-loveseat.glb",
    available: false,
    defaultUvScaleMm: 900,
    nativeSizeMm: { widthMm: 1650, heightMm: 790, depthMm: 860 },
    materialGroups: { upholstery: "upholstery", legs: "legs" },
  },
  {
    id: "model:lounge-chair",
    name: "Lounge Chair",
    catalogItemId: "living:lounge-chair",
    assetKey: "models/soft-goods/lounge-chair.glb",
    available: true,
    defaultUvScaleMm: 700,
    nativeSizeMm: { widthMm: 820, heightMm: 880, depthMm: 860 },
    materialGroups: { upholstery: "upholstery", frame: "frame" },
  },
  {
    id: "model:accent-chair",
    name: "Accent Chair",
    catalogItemId: "living:accent-chair",
    assetKey: "models/soft-goods/accent-chair.glb",
    available: false,
    defaultUvScaleMm: 700,
    nativeSizeMm: { widthMm: 760, heightMm: 820, depthMm: 780 },
    materialGroups: { upholstery: "upholstery", frame: "frame" },
  },
  {
    id: "model:coffee-table",
    name: "Coffee Table",
    catalogItemId: "living:coffee-table",
    assetKey: "models/soft-goods/coffee-table.glb",
    available: true,
    defaultUvScaleMm: 800,
    nativeSizeMm: { widthMm: 1200, heightMm: 380, depthMm: 650 },
    materialGroups: { top: "top", frame: "frame" },
  },
  {
    id: "model:coffee-table-round",
    name: "Round Coffee Table",
    catalogItemId: "living:coffee-table-round",
    assetKey: "models/soft-goods/coffee-table-round.glb",
    available: false,
    defaultUvScaleMm: 800,
    nativeSizeMm: { widthMm: 900, heightMm: 360, depthMm: 900 },
    materialGroups: { top: "top", frame: "frame" },
  },
  {
    id: "model:side-table",
    name: "Side Table",
    catalogItemId: "living:side-table",
    assetKey: "models/soft-goods/side-table.glb",
    available: true,
    defaultUvScaleMm: 600,
    nativeSizeMm: { widthMm: 480, heightMm: 520, depthMm: 480 },
    materialGroups: { top: "top", frame: "frame" },
  },
  {
    id: "model:console-table",
    name: "Console Table",
    catalogItemId: "living:console-table",
    assetKey: "models/soft-goods/console-table.glb",
    available: false,
    defaultUvScaleMm: 800,
    nativeSizeMm: { widthMm: 1500, heightMm: 780, depthMm: 360 },
    materialGroups: { top: "top", frame: "frame" },
  },
  {
    id: "model:ottoman",
    name: "Ottoman",
    catalogItemId: "living:ottoman",
    assetKey: "models/soft-goods/ottoman.glb",
    available: false,
    defaultUvScaleMm: 500,
    nativeSizeMm: { widthMm: 820, heightMm: 420, depthMm: 620 },
    materialGroups: { upholstery: "upholstery", base: "base" },
  },
  {
    id: "model:floor-lamp",
    name: "Floor Lamp",
    catalogItemId: "living:floor-lamp",
    assetKey: "models/soft-goods/floor-lamp.glb",
    available: true,
    defaultUvScaleMm: 500,
    nativeSizeMm: { widthMm: 420, heightMm: 1650, depthMm: 420 },
    materialGroups: { frame: "frame", shade: "shade" },
  },
  {
    id: "model:indoor-plant",
    name: "Indoor Plant",
    catalogItemId: "living:indoor-plant",
    assetKey: "models/soft-goods/indoor-plant.glb",
    available: true,
    defaultUvScaleMm: 600,
    nativeSizeMm: { widthMm: 720, heightMm: 1450, depthMm: 720 },
    materialGroups: { foliage: "foliage", planter: "planter" },
  },
] as const satisfies readonly ModelAssetDefinition[];
