/**
 * Re-writes the rect-kitchen CubiCasa-class fixture (no model weights).
 * Run: node scripts/gemini-floorplan/cubicasa_spike/write_example_fixture.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "../../../public/experiments/gemini-floorplan/fixtures/cubicasa");
mkdirSync(outDir, { recursive: true });

const fixture = {
  source: "fixture",
  imageWidthPx: 640,
  imageHeightPx: 480,
  notes: [
    "Offline CubiCasa-class spike fixture (not real CubiCasa weights).",
    "Generated by write_example_fixture.mjs",
  ],
  polygons: [
    { class: "wall", pointsPx: [{ x: 80, y: 80 }, { x: 560, y: 80 }] },
    { class: "wall", pointsPx: [{ x: 560, y: 80 }, { x: 560, y: 400 }] },
    { class: "wall", pointsPx: [{ x: 560, y: 400 }, { x: 80, y: 400 }] },
    { class: "wall", pointsPx: [{ x: 80, y: 400 }, { x: 80, y: 80 }] },
    { class: "door", pointsPx: [{ x: 200, y: 80 }, { x: 280, y: 80 }] },
    { class: "window", pointsPx: [{ x: 560, y: 160 }, { x: 560, y: 260 }] },
  ],
};

writeFileSync(join(outDir, "rect-kitchen.model.json"), JSON.stringify(fixture, null, 2) + "\n");
console.log("Wrote", join(outDir, "rect-kitchen.model.json"));
