import { LIVING_ROOM_MATERIAL_IDS } from "../../livingRoom/materials";
import type { ApartmentTemplateSpec } from "../types";

/** Studio ≈ 6000×5400 (32 m²). Nordic light · day · daylight (§4). */
export const STUDIO_SHELL_SPEC: ApartmentTemplateSpec = {
  id: "template:apartment:studio:v1",
  name: "Studio · Nordic light",
  description: "Open studio with bath and kitchenette strip",
  styleId: "nordic-light",
  lightingRecipeId: "daylight",
  mood: "day",
  shell: {
    widthMm: 6000,
    depthMm: 5400,
    heightMm: 2850,
    externalWallMm: 230,
    internalWallMm: 115,
  },
  splits: [
    {
      key: "front-back",
      inCell: "root",
      axis: "z",
      atMm: -900,
      cells: ["back", "front"],
    },
    {
      key: "bath-entry",
      inCell: "back",
      axis: "x",
      atMm: -900,
      cells: ["bath", "entry"],
    },
  ],
  rooms: [
    {
      key: "bath",
      cell: "bath",
      name: "Bath",
      roomType: "bathroom",
      floorMaterialId: LIVING_ROOM_MATERIAL_IDS.warmStone,
      compose: {
        kind: "bathroom",
        options: { vanitySide: "north", mirrorRopeLight: true, downlight: true },
      },
      camera: {
        eyeMm: { x: -1400, y: 1600, z: -1100 },
        targetMm: { x: -2200, y: 1100, z: -2000 },
      },
    },
    {
      key: "entry",
      cell: "entry",
      name: "Kitchenette",
      roomType: "kitchen",
      floorMaterialId: LIVING_ROOM_MATERIAL_IDS.warmStone,
      compose: {
        kind: "kitchen",
        options: {
          layout: "straight",
          runSide: "north",
          wallCabinets: true,
          tallPantry: false,
          frontSystem: "gola",
          doorStyle: "slab",
          doorSourcing: "in-house",
          underCabinetLights: true,
          profileLight: true,
          downlight: true,
        },
      },
      camera: {
        eyeMm: { x: 1050, y: 1600, z: -1050 },
        targetMm: { x: 1050, y: 1000, z: -2200 },
      },
    },
    {
      key: "living",
      cell: "front",
      name: "Living",
      roomType: "living-room",
      floorMaterialId: LIVING_ROOM_MATERIAL_IDS.warmStone,
      compose: {
        kind: "living",
        options: {
          tvWallSide: "north",
          featureWallPreset: "slat",
          displayNiche: false,
          wardrobeSide: "east",
          wardrobeWidthMm: 1800,
          wardrobeDoors: "sliding",
          sofaSet: true,
          coveLight: true,
          downlight: true,
        },
      },
      camera: {
        eyeMm: { x: 400, y: 1600, z: 2200 },
        targetMm: { x: 0, y: 1000, z: -400 },
      },
    },
  ],
  openings: [
    {
      kind: "opening",
      between: ["entry", "living"],
      offsetMm: 400,
      widthMm: 1200,
      heightMm: 2100,
    },
    {
      kind: "door",
      between: ["bath", "entry"],
      offsetMm: 200,
      widthMm: 800,
      heightMm: 2100,
    },
    {
      kind: "door",
      between: { room: "entry", side: "north" },
      offsetMm: 2800,
      widthMm: 900,
      heightMm: 2100,
    },
    {
      kind: "window",
      between: { room: "living", side: "south" },
      offsetMm: 2100,
      widthMm: 1800,
      heightMm: 1400,
      sillHeightMm: 900,
    },
    {
      kind: "window",
      between: { room: "entry", side: "east" },
      offsetMm: 350,
      widthMm: 1000,
      heightMm: 1200,
      sillHeightMm: 900,
    },
    {
      kind: "window",
      between: { room: "bath", side: "west" },
      offsetMm: 500,
      widthMm: 500,
      heightMm: 500,
      sillHeightMm: 1800,
    },
  ],
  heroRoomKey: "living",
  finishRoles: {
    carcass: LIVING_ROOM_MATERIAL_IDS.naturalOak,
    "front-primary": LIVING_ROOM_MATERIAL_IDS.naturalOak,
    "front-accent": LIVING_ROOM_MATERIAL_IDS.naturalOak,
    worktop: LIVING_ROOM_MATERIAL_IDS.warmStone,
    "wall-panel": LIVING_ROOM_MATERIAL_IDS.naturalOak,
    floor: LIVING_ROOM_MATERIAL_IDS.warmStone,
  },
};
